---
title: "StairwayPlot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
swUga <- read.csv("Stairway plot for Uganda.final.summary", sep = "\t")
swNam <- read.csv("Stairway plot for Namibia.final.summary", sep = "\t")
swTan <- read.csv("Stairway plot for Tanzania.final.summary", sep = "\t")
swZim <- read.csv("Stairway plot for Zimbabwe.final.summary", sep = "\t")
#swGha <- read.csv("Stairway plot for Ghana.final.summary", sep = "\t")
swUga$pop <- "Uga"
swNam$pop <- "Nam"
swTan$pop <- "Tan"
swZim$pop <- "Zim"
#swGha$pop <- "Gha"

sw <- rbind(swUga, swNam, swTan, swZim)
#sw$year <- sw$year + 1

ggplot(sw, aes(x = year, y = Ne_median, color = pop)) +
  geom_line() +
  scale_x_continuous(trans='log10', limits = c(1,50000)) +
  scale_y_continuous(trans='log10')

ggplot(sw, aes(x = year, y = Ne_median, color = pop)) +
  geom_line() +
  scale_y_continuous(trans='log10')

ggplot(sw, aes(x = year, y = Ne_median, color = pop)) +
  geom_line() +
  scale_x_continuous(trans='log10', limits = c(1,50000))


```

